/** Comma-separated SEO keywords for meta tags (deduplicated). */
export const SITE_KEYWORDS = [
  "tap2crack",
  "Tap2Crack",
  "tap2",
  "tap 2 crack",
  "egg game",
  "egg cracking game",
  "egg clicker game",
  "egg hatching game",
  "egg collecting game",
  "egg adventure game",
  "egg puzzle game",
  "egg challenge",
  "egg rewards",
  "lucky egg",
  "virtual egg",
  "golden egg",
  "mystery egg",
  "egg hunt",
  "egg arcade",
  "egg simulator",
  "egg quest",
  "egg launcher",
  "egg runner",
  "egg match game",
  "egg tapping game",
  "egg smash game",
  "egg breaker",
  "egg collector",
  "egg kingdom",
  "egg treasure",
  "egg jackpot",
  "egg bonus",
  "egg rewards game",
  "online egg game",
  "free egg game",
  "multiplayer egg game",
  "mobile egg game",
  "browser egg game",
  "fun egg game",
  "addictive egg game",
  "casual egg game",
  "family egg game",
  "kids egg game",
  "easter egg game",
  "egg race",
  "egg mystery",
  "egg challenge online",
  "hatch eggs",
  "collect eggs",
  "win rewards",
  "surprise eggs",
  "egg rewards platform",
  "virtual pet eggs",
  "egg farming",
  "egg incubator",
  "egg strategy game",
  "egg leaderboard",
  "egg competitions",
  "egg missions",
  "egg levels",
  "egg upgrades",
  "egg achievements",
  "egg prizes",
  "egg collection",
  "reward game",
  "lucky game",
  "prize game",
  "arcade rewards",
  "online rewards",
  "daily rewards",
  "bonus rewards",
  "fun challenges",
  "casual gaming",
  "free online games",
  "game rewards",
  "digital rewards",
  "play and win",
  "entertainment platform",
  "browser entertainment",
  "mobile entertainment",
  "gaming platform",
  "virtual rewards",
  "click and win",
  "collection game",
  "progression game",
  "discount store",
  "online discount store",
  "discount shopping",
  "bargain store",
  "cheap deals",
  "daily deals",
  "flash sales",
  "clearance sale",
  "clearance store",
  "outlet store",
  "low price store",
  "budget shopping",
  "affordable shopping",
  "discount marketplace",
  "shopping deals",
  "best discounts",
  "online bargains",
  "coupon deals",
  "promo deals",
  "special offers",
  "exclusive discounts",
  "save money",
  "shopping savings",
  "value shopping",
  "affordable products",
  "cheap products",
  "sale items",
  "discount products",
  "discount retailer",
  "online retailer",
  "wholesale deals",
  "retail discounts",
  "shopping promotions",
  "top deals",
  "best offers",
  "markdown sale",
  "discounted items",
  "seasonal sale",
  "bulk discounts",
  "clearance discounts",
  "limited time offers",
  "online savings",
  "budget marketplace",
  "shopping outlet",
  "cheap electronics",
  "discounted electronics",
  "cheap fashion",
  "discounted fashion",
  "home essentials sale",
  "kitchen deals",
  "furniture discounts",
  "beauty deals",
  "grocery discounts",
  "travel deals",
  "tech deals",
  "gadget deals",
  "office supply discounts",
  "online coupons",
  "voucher codes",
  "promo codes",
  "cashback offers",
  "shopping rewards",
  "loyalty rewards",
  "bargain hunter",
  "smart shopping",
  "price reduction",
  "low cost shopping",
  "best value deals",
  "affordable lifestyle",
  "mega sale",
  "super sale",
  "weekend sale",
  "holiday sale",
  "black friday deals",
  "cyber monday deals",
  "clearance event",
  "special promotion",
  "online store",
  "ecommerce deals",
  "shopping website",
  "best prices",
  "price comparison",
  "cheap online shopping",
  "affordable online store",
  "discount center",
  "savings hub",
  "value store",
  "discount warehouse",
  "deal finder",
  "bargain marketplace",
  "smart buyer",
  "money saving tips",
  "everyday discounts",
  "daily bargains",
  "unbeatable prices",
  "lowest prices",
  "quality discounts",
  "trusted discount store",
  "deal of the day",
  "shopping specials",
  "discount offers",
  "bulk savings",
  "online marketplace",
  "shopping club",
  "clearance marketplace",
  "discounted brands",
  "premium products discount",
  "family savings",
  "budget deals",
  "affordable brands",
  "economical shopping",
  "tap to crack",
  "tap and crack",
  "crack the egg",
  "egg tap game",
  "tap egg challenge",
  "crack eggs online",
  "egg breaker game",
  "egg smashing game",
  "egg clicker",
  "egg tapper",
  "egg cracking challenge",
  "lucky egg crack",
  "surprise egg crack",
  "egg reward game",
  "crack and win",
  "tap to win",
  "crack for rewards",
  "crack mystery egg",
  "golden egg crack",
  "egg popping game",
  "cracking eggs for prizes",
  "instant win egg game",
  "tap crack collect",
  "egg cracking fun",
  "free egg cracking game",
  "online egg cracking",
  "egg crack rewards",
  "daily egg crack",
  "egg jackpot game",
  "lucky egg tap",
  "crack the golden egg",
  "egg hunt rewards",
  "crack eggs and win",
  "virtual egg crack",
  "tap crack surprise",
  "egg bonus game",
  "interactive egg game",
  "addictive egg crack game",
  "one tap egg game",
  "mobile egg cracking game",
  "egg cracking rewards",
  "lucky reward eggs",
  "egg tapping rewards",
  "crack and collect",
  "crack and earn",
  "fun egg challenge",
  "egg cracking adventure",
  "egg jokes",
  "funny egg jokes",
  "egg puns",
  "egg humor",
  "egg comedy",
  "egg one liners",
  "egg memes",
  "egg laugh jokes",
  "egg cracking jokes",
  "eggcellent jokes",
  "eggstra funny",
  "egg pun collection",
  "easter egg jokes",
  "yolk jokes",
  "egg themed jokes",
  "shell jokes",
  "sunny side up jokes",
  "breakfast jokes",
  "chicken and egg jokes",
  "family egg jokes",
  "kids egg jokes",
  "clean egg jokes",
  "hilarious egg jokes",
  "funny yolk jokes",
  "egg wordplay",
  "egg giggles",
  "egg laugh challenge",
  "egg joke of the day",
  "cheesy egg jokes",
  "egg humor collection",
  "egg pun game",
  "cracking good jokes",
  "egg meme jokes",
  "viral egg jokes",
  "egg funnies",
  "joke eggs",
  "egg entertainment",
  "joke challenge",
  "daily egg laugh",
  "funny egg quotes",
  "egg gags",
  "yolk humor",
  "egg laughter",
  "egg jokes for kids",
  "family friendly jokes",
  "egg pun memes",
  "funny breakfast jokes",
  "egg comic humor",
  "egg joke website",
  "virtual egg rewards",
  "lucky egg game",
  "surprise egg game",
  "reward game online",
  "play egg game online",
  "free rewards game",
  "instant reward game",
  "egg bonus rewards",
  "crack eggs and earn",
  "clicker egg game",
  "lucky rewards",
  "daily rewards game",
  "mystery egg rewards",
  "virtual prizes",
  "entertainment rewards",
  "gaming rewards",
  "family game",
  "reward challenges",
  "online entertainment",
  "egg adventure",
  "egg quests",
  "puzzle egg game",
  "egg treasure hunt",
  "daily challenges",
  "lucky draw game",
  "instant win game",
  "reward collection",
  "online fun",
  "egg website SEO",
  "egg game website",
  "egg entertainment site",
  "fun reward platform",
  "egg themed website",
  "viral egg game",
  "trending egg game",
  "egg content",
  "egg community",
  "egg fun zone",
  "yokes",
  "discount",
  "shop",
  "Netflix",
  "honey",
  "win money",
  "airtime",
  "coupons",
  "vouchers",
  "tickets",
  "prizes",
  "play to win",
].join(", ");

export const SITE_DESCRIPTION =
  "Tap2Crack is a free online egg cracking game — tap to crack, hatch, and collect lucky eggs to win money, airtime, coupons, vouchers, and daily rewards. Play the addictive egg tapper on mobile or browser: crack mystery and golden eggs, climb the leaderboard, enjoy egg jokes, and shop discount deals on Nigeria's fun reward platform.";

export const SITE_TITLE =
  "Tap2Crack | Egg Cracking Game — Tap, Crack, Win Rewards, Coupons & Deals";

export const OG_TITLE =
  "Tap2Crack — Egg Tapping Game | Crack Eggs, Win Money, Airtime & Discount Coupons";

export const OG_DESCRIPTION =
  "Play the free egg clicker game online. Tap to crack eggs, win rewards, collect prizes, enjoy egg jokes, and unlock discount coupons — multiplayer egg adventure on mobile and browser.";
